
# TODO change to Pre-Build, Build, Build Image
stages:
  - Build Prerequisites
  - Build Docker Image


services:
  - docker:18.03-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""


build_test_base:
  stage: Build Prerequisites
  only:
    - test
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --cache-ttl=24h --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/test-base.Dockerfile --destination $CI_REGISTRY_IMAGE:test-base

build_test_image:
  stage: Build Docker Image
  only:
    - ci
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    #- tar -cvf app.tar api/ http/
    - tar -cvf app.tar api/
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - sleep 1000
    #- /kaniko/executor --cache=true --cache-ttl=24h --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/test.Dockerfile --destination $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:test
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/test.Dockerfile --destination $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:test
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Use this line for the first build
    #- docker build --network=host --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # Use these 2 lines after the first build to speed up the build in the future
    #- docker pull $CI_REGISTRY_IMAGE:latest
    #- docker build --network=host --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    #- docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    #- docker push $CI_REGISTRY_IMAGE:latest


build_node:
  stage: Build Prerequisites
  only:
    - staging
    - production
    - test
  image: node:15.5.0  # previously 14.8.0
  # Required if you separate the UI and backend repo
  #variables:
  #  GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - http
  cache:
    key: "node_modules"
    paths:
      - ui/node_modules
  script:
    #- sleep 600
    - cd ui
    - yarn install --network-timeout 600000  # 600000ms == 10 min; required as a workaround for @material-ui/icons
    - CI=false yarn build
    - mv build ../http


build_image:
  stage: Build Docker Image
  only:
    - staging
    - production
  image: docker
  script:
    - tar -cvf app.tar api/ http/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Use this line for the first build
    - docker build --network=host --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # Use these 2 lines after the first build to speed up the build in the future
    #- docker pull $CI_REGISTRY_IMAGE:latest
    #- docker build --network=host --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

