# Generated by Django 3.2.7 on 2021-09-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguarduser',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR Code'),
        ),
    ]
