# Generated by Django 3.2.7 on 2021-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsvpn', '0002_auto_20210920_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardserver',
            name='default',
            field=models.BooleanField(default=False, help_text='Default server when creating new peers.', verbose_name='Default Server'),
        ),
    ]
