# Generated by Django 3.2.7 on 2021-09-21 01:13

from django.db import migrations, models
import django.db.models.deletion
import letsvpn.WireguardServer.models


class Migration(migrations.Migration):

    dependencies = [
        ('letsvpn', '0003_alter_wireguardserver_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(default=letsvpn.WireguardServer.models.WireguardServer.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='server', to='letsvpn.wireguardserver'),
        ),
    ]
