# Generated by Django 3.2.7 on 2021-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsvpn', '0004_alter_wireguardpeer_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardpeer',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this peer enabled in the server config? (Will not be able to connect when disabled)', verbose_name='Enabled'),
        ),
    ]
