# Generated by Django 3.2.7 on 2021-10-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsvpn', '0005_wireguardpeer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardserver',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this peer enabled in the server config? (Will not be able to connect when disabled)', verbose_name='Enabled'),
        ),
    ]
