# Generated by Django 3.2.7 on 2021-09-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gravatar',
            field=models.URLField(blank=True, null=True, verbose_name='Gravatar URL'),
        ),
    ]
